# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktopUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BG_1 = QtWidgets.QLabel(self.centralwidget)
        self.BG_1.setGeometry(QtCore.QRect(-730, 20, 2131, 1331))
        self.BG_1.setText("")
        self.BG_1.setPixmap(QtGui.QPixmap("../project images/B.G/Black_Template.jpg"))
        self.BG_1.setScaledContents(True)
        self.BG_1.setObjectName("BG_1")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(20, 440, 271, 41))
        self.bg_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("../project images/text browser bg.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(20, 490, 271, 41))
        self.bg_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("../project images/text browser bg.jpg"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(20, 540, 271, 41))
        self.bg_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.bg_3.setText("")
        self.bg_3.setPixmap(QtGui.QPixmap("../project images/text browser bg.jpg"))
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")
        self.Text_day = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_day.setGeometry(QtCore.QRect(20, 440, 271, 41))
        self.Text_day.setStyleSheet("background-color:Transparent;\n"
"border radius:none;")
        self.Text_day.setObjectName("Text_day")
        self.Text_date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_date.setGeometry(QtCore.QRect(20, 490, 271, 41))
        self.Text_date.setStyleSheet("background-color:Transparent;\n"
"border radius:none;")
        self.Text_date.setObjectName("Text_date")
        self.Text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_time.setGeometry(QtCore.QRect(20, 540, 271, 41))
        self.Text_time.setStyleSheet("background-color:Transparent;\n"
"border radius:none;")
        self.Text_time.setObjectName("Text_time")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(1010, 130, 121, 51))
        self.pushButton_Start.setStyleSheet("background-color: Transparent;\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(255, 0, 0);")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.Bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_1.setGeometry(QtCore.QRect(10, 0, 311, 381))
        self.Bg_1.setStyleSheet("background-color: rgb(52, 0, 0);")
        self.Bg_1.setText("")
        self.Bg_1.setObjectName("Bg_1")
        self.Bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_3.setGeometry(QtCore.QRect(380, 0, 321, 381))
        self.Bg_3.setStyleSheet("background-color: rgb(38, 0, 0);\n"
"")
        self.Bg_3.setText("")
        self.Bg_3.setObjectName("Bg_3")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(330, 440, 361, 141))
        self.bg_4.setStyleSheet("background-color: rgb(38, 0, 0);")
        self.bg_4.setObjectName("bg_4")
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(1160, 140, 141, 41))
        self.pushButton_Exit.setStyleSheet("background-color: Transparent;\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(255, 0, 0);")
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.pushButton_Youtube = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Youtube.setGeometry(QtCore.QRect(760, 0, 171, 51))
        self.pushButton_Youtube.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(144, 144, 255);")
        self.pushButton_Youtube.setObjectName("pushButton_Youtube")
        self.pushButton_Chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Chrome.setGeometry(QtCore.QRect(940, 0, 171, 51))
        self.pushButton_Chrome.setStyleSheet("background-color: rgb(144, 144, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_Chrome.setObjectName("pushButton_Chrome")
        self.pushButton_Whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Whatsapp.setGeometry(QtCore.QRect(1120, 0, 171, 51))
        self.pushButton_Whatsapp.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(144, 144, 255);")
        self.pushButton_Whatsapp.setObjectName("pushButton_Whatsapp")
        self.pushButton_Google = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Google.setGeometry(QtCore.QRect(760, 60, 171, 51))
        self.pushButton_Google.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(144, 144, 255);")
        self.pushButton_Google.setObjectName("pushButton_Google")
        self.pushButton_VSCode = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_VSCode.setGeometry(QtCore.QRect(940, 60, 171, 51))
        self.pushButton_VSCode.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(144, 144, 255);")
        self.pushButton_VSCode.setObjectName("pushButton_VSCode")
        self.pushButton_Temperature = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Temperature.setGeometry(QtCore.QRect(1120, 60, 171, 51))
        self.pushButton_Temperature.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(144, 144, 255);")
        self.pushButton_Temperature.setObjectName("pushButton_Temperature")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(760, 210, 221, 171))
        self.bg_5.setStyleSheet("background-color: rgb(38, 0, 0);")
        self.bg_5.setObjectName("bg_5")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(1040, 240, 251, 111))
        self.bg_6.setObjectName("bg_6")
        self.gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.gif_5.setGeometry(QtCore.QRect(1040, 220, 311, 131))
        self.gif_5.setText("")
        self.gif_5.setPixmap(QtGui.QPixmap("../project images/initial.gif"))
        self.gif_5.setScaledContents(True)
        self.gif_5.setObjectName("gif_5")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(360, 0, 361, 391))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("../project images/200.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(330, 430, 361, 141))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("../project images/audio.gif"))
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(760, 210, 221, 171))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("../project images/giphy.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(6, 0, 321, 381))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("../project images/girl assistant.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 410, 511, 161))
        self.label.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.label.setObjectName("label")
        self.terminalOutputBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.terminalOutputBox.setGeometry(QtCore.QRect(740, 410, 511, 131))
        self.terminalOutputBox.setStyleSheet("background-color: transpaent;\n"
"")
        self.terminalOutputBox.setObjectName("terminalOutputBox")
        self.TerminalInputBox = QtWidgets.QLineEdit(self.centralwidget)
        self.TerminalInputBox.setGeometry(QtCore.QRect(740, 540, 511, 31))
        self.TerminalInputBox.setStyleSheet("background-color: transparent;")
        self.TerminalInputBox.setObjectName("TerminalInputBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.ManicUi = QtWidgets.QStatusBar(MainWindow)
        self.ManicUi.setObjectName("ManicUi")
        MainWindow.setStatusBar(self.ManicUi)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.bg_4.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_Exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_Youtube.setText(_translate("MainWindow", "YouTube"))
        self.pushButton_Chrome.setText(_translate("MainWindow", "Chrome"))
        self.pushButton_Whatsapp.setText(_translate("MainWindow", "WhatsApp"))
        self.pushButton_Google.setText(_translate("MainWindow", "Google"))
        self.pushButton_VSCode.setText(_translate("MainWindow", "VSCode"))
        self.pushButton_Temperature.setText(_translate("MainWindow", "Temperature"))
        self.bg_5.setText(_translate("MainWindow", "TextLabel"))
        self.bg_6.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
