# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faceRecognition.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BG_1 = QtWidgets.QLabel(self.centralwidget)
        self.BG_1.setGeometry(QtCore.QRect(-50, -270, 1361, 911))
        self.BG_1.setText("")
        self.BG_1.setPixmap(QtGui.QPixmap("../project images/B.G/Black_Template.jpg"))
        self.BG_1.setScaledContents(True)
        self.BG_1.setObjectName("BG_1")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(290, 30, 621, 91))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("../project images/WhatsApp Image 2023-05-14 at 9.54.19 PM.jpeg"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(370, 480, 111, 51))
        self.loginButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Decorated035 BT\";\n"
"background-color: rgb(0, 0, 54);")
        self.loginButton.setObjectName("loginButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(550, 480, 111, 51))
        self.exitButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Decorated035 BT\";\n"
"background-color: rgb(0, 0, 54);")
        self.exitButton.setObjectName("exitButton")
        self.videolable = QtWidgets.QLabel(self.centralwidget)
        self.videolable.setGeometry(QtCore.QRect(550, 140, 431, 281))
        self.videolable.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.videolable.setText("")
        self.videolable.setPixmap(QtGui.QPixmap("../project images/d96a6aee47ff63f4634d985964d49009.jpg"))
        self.videolable.setScaledContents(True)
        self.videolable.setObjectName("videolable")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(146, 142, 381, 331))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("../project images/0_7D1L1pV21MIp46zG.gif"))
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginButton.setText(_translate("MainWindow", "LOGIN"))
        self.exitButton.setText(_translate("MainWindow", "EXIT"))
