# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BG__1 = QtWidgets.QLabel(self.centralwidget)
        self.BG__1.setGeometry(QtCore.QRect(-170, -100, 1361, 721))
        self.BG__1.setText("")
        self.BG__1.setPixmap(QtGui.QPixmap("../project images/B.G/Black_Template.jpg"))
        self.BG__1.setScaledContents(True)
        self.BG__1.setObjectName("BG__1")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(110, 10, 591, 101))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../project images/WhatsApp Image 2023-05-14 at 9.54.19 PM.jpeg"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.GUI_1 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_1.setGeometry(QtCore.QRect(6, 112, 841, 341))
        self.GUI_1.setText("")
        self.GUI_1.setPixmap(QtGui.QPixmap("project images/1666200990801.gif"))
        self.GUI_1.setScaledContents(True)
        self.GUI_1.setObjectName("GUI_1")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 490, 161, 51))
        self.pushButton.setStyleSheet("font: 18pt \"Decorated035 BT\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 82, 120);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 490, 161, 51))
        self.pushButton_2.setStyleSheet("font: 18pt \"Decorated035 BT\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 82, 120);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 490, 161, 51))
        self.pushButton_3.setStyleSheet("font: 18pt \"Decorated035 BT\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 82, 120);")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_3.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
