# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BG__1 = QtWidgets.QLabel(self.centralwidget)
        self.BG__1.setGeometry(QtCore.QRect(-44, -160, 1361, 761))
        self.BG__1.setText("")
        self.BG__1.setPixmap(QtGui.QPixmap("../project images/B.G/Black_Template.jpg"))
        self.BG__1.setScaledContents(True)
        self.BG__1.setObjectName("BG__1")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(370, 150, 491, 341))
        self.mainFrame.setStyleSheet("background-color: rgb(0, 0, 75);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.usernameEntry = QtWidgets.QLineEdit(self.mainFrame)
        self.usernameEntry.setGeometry(QtCore.QRect(100, 60, 301, 41))
        self.usernameEntry.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.usernameEntry.setObjectName("usernameEntry")
        self.passwordEntry = QtWidgets.QLineEdit(self.mainFrame)
        self.passwordEntry.setGeometry(QtCore.QRect(100, 120, 301, 41))
        self.passwordEntry.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.passwordEntry.setObjectName("passwordEntry")
        self.loginButton = QtWidgets.QPushButton(self.mainFrame)
        self.loginButton.setGeometry(QtCore.QRect(200, 190, 111, 31))
        self.loginButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Decorated035 BT\";")
        self.loginButton.setObjectName("loginButton")
        self.retryButton = QtWidgets.QPushButton(self.mainFrame)
        self.retryButton.setGeometry(QtCore.QRect(30, 290, 111, 31))
        self.retryButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Decorated035 BT\";")
        self.retryButton.setObjectName("retryButton")
        self.backButton = QtWidgets.QPushButton(self.mainFrame)
        self.backButton.setGeometry(QtCore.QRect(190, 290, 111, 31))
        self.backButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Decorated035 BT\";")
        self.backButton.setObjectName("backButton")
        self.exitButton = QtWidgets.QPushButton(self.mainFrame)
        self.exitButton.setGeometry(QtCore.QRect(350, 290, 111, 31))
        self.exitButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Decorated035 BT\";")
        self.exitButton.setObjectName("exitButton")
        self.Name = QtWidgets.QLabel(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(316, 32, 571, 71))
        self.Name.setText("")
        self.Name.setPixmap(QtGui.QPixmap("../project images/WhatsApp Image 2023-05-14 at 9.54.19 PM.jpeg"))
        self.Name.setScaledContents(True)
        self.Name.setObjectName("Name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernameEntry.setText(_translate("MainWindow", "USERNAME"))
        self.passwordEntry.setText(_translate("MainWindow", "PASSWORD"))
        self.loginButton.setText(_translate("MainWindow", "LOGIN"))
        self.retryButton.setText(_translate("MainWindow", "RETRY"))
        self.backButton.setText(_translate("MainWindow", "BACK"))
        self.exitButton.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
